import React from "react";
import Head from "next/head";
import { StoriesBanner } from "@/modules/Molecules/";
import { Header, Footer } from "@/modules/Organism/";
import { FeatureSection, IntroText } from "@/components/Homepage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <IntroText />
        <StoriesBanner />
        <FeatureSection />
        <Footer />
      </main>
    </>
  );
}
