import { GetStaticPaths, GetStaticProps } from "next";
import React from "react";
import { getSortedJobsData } from "../../../lib/jobs";
import Head from "next/head";
import { Header } from "@/modules/Organism";

interface JobPageProps {
  job: Job;
}

const JobPage = ({ job }: JobPageProps) => {
  return (
    <>
      <Head>
        <title>{job.id}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div style={{ marginTop: "180px" }}>{job.title}</div>
      </main>
    </>
  );
};

export default JobPage;

export const getStaticPaths: GetStaticPaths = () => {
  const jobs = getSortedJobsData();
  const paths = jobs.map((job) => ({
    params: { id: job.id },
  }));
  return { paths, fallback: false };
};

export const getStaticProps: GetStaticProps = ({ params }) => {
  const jobs = getSortedJobsData();
  if (params) {
    const currentJob = jobs.find((job) => job.id === params.id);
    return {
      props: { job: currentJob },
    };
  } else {
    return {
      props: { job: "ciao" },
    };
  }
};
